on: workflow_dispatch
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - name: cache primes
    id: cache-primes
    uses: actions/cache@v3
    with:
     path: primes
     key: ${{runner.os}}-primes
  - name: generate primes
    if: steps.cache-primes.outputs.cache-hit != 'true'
    run : |
     sleep 60
     echo "1,2,3..." > primes
  - name: use prime numbers
    run: cat primes
     
