name: dependency-needs
on: workflow_dispatch
jobs:
 initial:
  runs-on : ubuntu-latest
  steps:
  - run: echo "This job will be run first"
 fanout1:
  runs-on : ubuntu-latest
  needs: initial
  steps:
  - run: echo "This job will be run after initial and in parallel with fanout2"
 fanout2:
  runs-on : ubuntu-latest
  needs: initial
  steps:
  - run: echo "This job will be run after initial and in parallel with fanout2"
 fanout3:
  runs-on : ubuntu-latest
  needs: [fanout1,fanout2]
  steps:
  - run: echo "This job will be run last"
  
